@baseUrl = http://localhost:3000/api

@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkyY2FkMGVjLTNmMzctNDY3OS05MTQ0LWJhMTBhY2E5ODA5NSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDQyOTk4ODYsImV4cCI6MTc0Njg5MTg4Nn0.MzPmzpO47HFG2Rm0sUF0K2f8c3EQTVSBv4clEe8qSI8

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExYzhjODc1LTMzOWUtNDBiYy05ZGM3LTdhZTczMDc5N2Q4NiIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQ0Mjk5OTQwLCJleHAiOjE3NDY4OTE5NDB9.K5Yt7ZVgHWXtgggFn0h3zoHG8pz89rIoP7BpryES7Ko

@customerId = 92cad0ec-3f37-4679-9144-ba10aca98095

@driverId = a1c8c875-339e-40bc-9dc7-7ae730797d86

@rideId = 6a02000c-0e47-4c1f-825c-85f046446c7f

@tripId = f2a4db09-1b5d-4ba9-97e4-e77121a28f5c

@previousRideId = 

### Ride Routes ###

### Create Ride Request
POST {{baseUrl}}/rides/request
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    "customerId": "{{customerId}}",
    "pickupLocation": {
        "lat": -2.00116,
        "lon": 30.14428,
        "address": "X4XV+RWV, Kigali "
    },
    "dropoffLocation": {
        "lat": -1.94441,
        "lon": 30.09065,
        "address": "KG 563 St, Kigali"
    }
}

### Accept Ride
PUT {{baseUrl}}/rides/accept
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "driverId": "{{driverId}}"
}

### Complete Ride
PUT {{baseUrl}}/rides/complete
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "finalAmount": 1105.456464858334
}

### Cancel Ride
PUT {{baseUrl}}/rides/cancel
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "tripId":"{{tripId}}",
  "canceledByType": "CUSTOMER",
  "canceledById": "{{customerId}}",
  "reason": "Customer changed their plans"
}

### Get Nearby Rides
GET {{baseUrl}}/rides/nearby?lat=-1.9403&lon=30.0619&radius=40
Authorization: Bearer {{driverToken}}

### Reorder Ride
POST {{baseUrl}}/rides/reorder
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "previousRideId": "{{previousRideId}}"
}
