@baseUrl = http://localhost:3000/api

@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRjNTRkZDJkLTgzYjQtNGM3Ny1iMzI4LTlmMTg2ZTAwODYyNiIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDIyOTg1NDksImV4cCI6MTc0NDg5MDU0OX0.WuWrfXK7OsOh9z_uuIkZCBCoFizl3rcVRB-tfklpbAY

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzE4M2RmLTExOGYtNDc1Ni05ODUwLTVjOGUyM2VkN2VjNSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQyMjk4NTEwLCJleHAiOjE3NDQ4OTA1MTB9.uo08Bk1JP6CFcl_KnRbGaN9imGrbde_uIciQVhHh1Hk

@customerId = dc54dd2d-83b4-4c77-b328-9f186e008626

@driverId = 6a3183df-118f-4756-9850-5c8e23ed7ec5

@vehicleId = 60610470-7be6-4127-bb3e-462657905fbe

@rideId = 698304fa-46eb-4435-b92f-415dadbd0092

@tripId = 01c48e5d-4261-4878-a7bf-f0b51d7dac7a

@previousRideId = 

### Ride Routes ###

### Create Ride Request
POST {{baseUrl}}/rides/request
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    "customerId": "{{customerId}}",
    "pickupLocation": {
        "lat": -2.00116,
        "lon": 30.14428,
        "address": "X4XV+RWV, Kigali "
    },
    "dropoffLocation": {
        "lat": -1.94441,
        "lon": 30.09065,
        "address": "KG 563 St, Kigali"
    }
}

### Accept Ride
PUT {{baseUrl}}/rides/accept
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "driverId": "{{driverId}}"
}

### Complete Ride
PUT {{baseUrl}}/rides/complete
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "finalAmount": 1105.456464858334
}

### Cancel Ride
PUT {{baseUrl}}/rides/cancel
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "tripId":"{{tripId}}",
  "canceledByType": "CUSTOMER",
  "canceledById": "{{customerId}}",
  "reason": "Customer changed their plans"
}

### Get Nearby Rides
GET {{baseUrl}}/rides/nearby?lat=-1.9403&lon=30.0619&radius=40
Authorization: Bearer {{driverToken}}

### Reorder Ride
POST {{baseUrl}}/rides/reorder
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "previousRideId": "{{previousRideId}}"
}
