@baseUrl = http://localhost:3000/api

@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRjNTRkZDJkLTgzYjQtNGM3Ny1iMzI4LTlmMTg2ZTAwODYyNiIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDIyOTg1NDksImV4cCI6MTc0NDg5MDU0OX0.WuWrfXK7OsOh9z_uuIkZCBCoFizl3rcVRB-tfklpbAY

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzE4M2RmLTExOGYtNDc1Ni05ODUwLTVjOGUyM2VkN2VjNSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQyMjk4NTEwLCJleHAiOjE3NDQ4OTA1MTB9.uo08Bk1JP6CFcl_KnRbGaN9imGrbde_uIciQVhHh1Hk

@customerId = dc54dd2d-83b4-4c77-b328-9f186e008626

@driverId = 6a3183df-118f-4756-9850-5c8e23ed7ec5

@vehicleId = 60610470-7be6-4127-bb3e-462657905fbe



### Vehicle Routes ###

### Create a new vehicle
POST {{baseUrl}}/vehicles
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "type": "CAR",
  "regNo": "RAC 456",
  "model": "Camry",
  "color": "Gold"
}

###

### Get all vehicles for a specific driver
GET {{baseUrl}}/vehicles/driver/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update a vehicle
PUT {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "type": "CAR",
  "model": "Camry",
  "color": "Black",
  "isActive": true
}

###

### Delete a vehicle
DELETE {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}

