@baseUrl = http://localhost:3000/api

@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlYWUxNWUwLTNjZGUtNDkxMC05NGM4LTUwYWYwMmYzNmRkOSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDA3NDE1NzAsImV4cCI6MTc0MzMzMzU3MH0.SJwDQAQD79IfTc35d4vxGXnV8i-QI1L1bRq2VHUhfEw

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYjBmMDY1LWIwYTktNDliZC05NjM4LWYzMTJkNzQ2OGQxNSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQwNzQxNjE0LCJleHAiOjE3NDMzMzM2MTR9.ppCV1Ins0zrODyGCd8T0oSsH2K9S4woETgS56X-8DPM

@customerId = 8eae15e0-3cde-4910-94c8-50af02f36dd9

@driverId = afb0f065-b0a9-49bd-9638-f312d7468d15


### Register Customer
POST {{baseUrl}}/auth/customer/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Customer",
    "email": "john.customer@example.com",
    "password": "securepassword123",
    "phone": "+1234567890"
}

###

### Login Customer
POST {{baseUrl}}/auth/customer/login HTTP/1.1
Content-Type: application/json

{
    "email": "john.customer@example.com",
    "password": "securepassword123"
}

###

### Register Driver
POST {{baseUrl}}/auth/driver/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Driver",
    "email": "john.driver@example.com",
    "password": "securepassword123",
    "phone": "+1234567890",
    "licenseNumber": "DL123456"
}

###

### Login Driver
POST {{baseUrl}}/auth/driver/login HTTP/1.1
Content-Type: application/json

{
    "email": "john.driver@example.com",
    "password": "securepassword123"
}



### Send OTP
POST {{baseUrl}}/auth/send-otp
Content-Type: application/json

{
    "userId": "{{customerId}}",
    "userType": "CUSTOMER",
    "email": "user@example.com"
}

### Verify OTP
POST {{baseUrl}}/auth/verify-otp
Content-Type: application/json

{
    "email": "user@example.com",
    "userType": "CUSTOMER",  // or "DRIVER"
    "otp": "123456"
}
