@baseUrl = http://localhost:3000/api
@authToken = 
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxZWMyMTFhLWUwMzktNGZhZi05OTFkLTY2N2RlZTA1MGQzNSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk1MTc3NzEsImV4cCI6MTc0MjEwOTc3MX0.a3JyMcbOdg1TBAivhVJFO9P8yFt8z_QRpMKEUHPNudw
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4YWU5ODM3LTFkMGYtNDAyNC1iMzczLWJjYTNjYTY0NzZhZSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5NTE3Nzk5LCJleHAiOjE3NDIxMDk3OTl9.23rYk_ry_e_WIKhwSy4QW496sDJB_5wYe2Q_24iAfDQ

@customerId = 41ec211a-e039-4faf-991d-667dee050d35
@driverId = 38ae9837-1d0f-4024-b373-bca3ca6476ae
@vehicleId = b65f06a3-ea66-43ae-a2b4-33a8180ebd5b

@rideId = d6edfcd4-849a-4f9d-9bfb-d5051d9a12b1

### Register Customer
POST {{baseUrl}}/auth/customer/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Customer",
    "email": "john.customer@example.com",
    "password": "securepassword123",
    "phone": "+1234567890"
}

###

### Login Customer
POST {{baseUrl}}/auth/customer/login HTTP/1.1
Content-Type: application/json

{
    "email": "john.customer@example.com",
    "password": "securepassword123"
}

###

### Register Driver
POST {{baseUrl}}/auth/driver/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Driver",
    "email": "john.driver@example.com",
    "password": "securepassword123",
    "phone": "+1234567890",
    "licenseNumber": "DL123456"
}

###

### Login Driver
POST {{baseUrl}}/auth/driver/login HTTP/1.1
Content-Type: application/json

{
    "email": "john.driver@example.com",
    "password": "securepassword123"
}



### Send OTP
POST {{baseUrl}}/auth/send-otp
Content-Type: application/json

{
    "userId": "{{customerId}}",
    "userType": "CUSTOMER",
    "email": "user@example.com"
}

### Verify OTP
POST {{baseUrl}}/auth/verify-otp
Content-Type: application/json

{
    "email": "user@example.com",
    "userType": "CUSTOMER",  // or "DRIVER"
    "otp": "123456"
}
