@baseUrl = http://localhost:3000/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNkNDQ3Mjg4LTMxODQtNGY3ZS04NDZjLTk3ZDJlNDc5YWEyNiIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MzkzMjAzMTcsImV4cCI6MTc0MTkxMjMxN30.BDS8XcSfkeFzYUFJykNbdLdE3dDhMy1EcfzXp8ZG6bw
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2ZTQyYzI1LTk3NjgtNDRkMC05YjY3LTZlMWQ2ZjJlMTFkZCIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5MzIwMjM3LCJleHAiOjE3NDE5MTIyMzd9.uvM3TacjZxkdSzfbxd0UU-21kC_xcQe3T559PIuLb6Y
@customerId = cd447288-3184-4f7e-846c-97d2e479aa26
@driverId = 26e42c25-9768-44d0-9b67-6e1d6f2e11dd
@vehicleId = b65f06a3-ea66-43ae-a2b4-33a8180ebd5b

@rideId = d6edfcd4-849a-4f9d-9bfb-d5051d9a12b1


### Forgot Password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
    "email": "user@example.com",
    "userType": "CUSTOMER"  // or "DRIVER"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
    "token": "reset-token-from-email",
    "userType": "CUSTOMER",  // or "DRIVER"
    "newPassword": "newpassword123"
}

