@baseUrl = http://localhost:3000/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZjAxODRlLTBmOWYtNDc2Zi1hOTBmLTAxYmNmYWUyMjU4MSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDA2Njg5NTMsImV4cCI6MTc0MzI2MDk1M30.JIoGtx4N7eosI6N4HHhvNXXJQF2SmbyOCh7eC15ZnXw
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyZTExOTQ3LWE2YjMtNDk1Yy1iOTUwLTE1NjM1Zjk3YmFlYSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQwNjY4OTg5LCJleHAiOjE3NDMyNjA5ODl9.RWDVxZub3iHGI3OOeIl9f7VlO5ofs90Hbb4RBqQXfOE

@customerId = 44f0184e-0f9f-476f-a90f-01bcfae22581

@driverId = a2e11947-a6b3-495c-b950-15635f97baea

@vehicleId = 33fbe171-1fef-4796-9929-e5b5618cb376

@rideId = 5e0a7b30-5755-4bff-8a41-56f1c1881e72

@tripId = dd020e87-f2bf-4b34-bb44-b3a420da3bc8

@previousRideId = 

### Ride Routes ###

### Create Ride Request
POST {{baseUrl}}/rides/request
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    "customerId": "{{customerId}}",
    "pickupLocation": {
        "lat": -1.9403,
        "lon": 30.0619,
        "address": "123 Main "
    },
    "dropoffLocation": {
        "lat": -1.9503,
        "lon": 30.0719,
        "address": "456 Elm St"
    }
}

### Accept Ride
PUT {{baseUrl}}/rides/accept
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "driverId": "{{driverId}}"
}

### Complete Ride
PUT {{baseUrl}}/rides/complete
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "finalAmount": 1105.456464858334
}

### Cancel Ride
PUT {{baseUrl}}/rides/cancel
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "tripId":"{{tripId}}",
  "canceledByType": "CUSTOMER",
  "canceledById": "{{customerId}}",
  "reason": "Customer changed their plans"
}

### Get Nearby Rides
GET {{baseUrl}}/rides/nearby?lat=-1.9403&lon=30.0619&radius=40
Authorization: Bearer {{driverToken}}

### Reorder Ride
POST {{baseUrl}}/rides/reorder
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "previousRideId": "{{previousRideId}}"
}
