@baseUrl = http://localhost:3000/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlYWUxNWUwLTNjZGUtNDkxMC05NGM4LTUwYWYwMmYzNmRkOSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDA3NDE1NzAsImV4cCI6MTc0MzMzMzU3MH0.SJwDQAQD79IfTc35d4vxGXnV8i-QI1L1bRq2VHUhfEw

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYjBmMDY1LWIwYTktNDliZC05NjM4LWYzMTJkNzQ2OGQxNSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQwNzQxNjE0LCJleHAiOjE3NDMzMzM2MTR9.ppCV1Ins0zrODyGCd8T0oSsH2K9S4woETgS56X-8DPM

@customerId = 8eae15e0-3cde-4910-94c8-50af02f36dd9

@driverId = afb0f065-b0a9-49bd-9638-f312d7468d15

@vehicleId = f9e7fb4b-1028-4a35-9b0b-06bb3b94124d

@rideId = 6790a7a4-ffd1-4ab0-b22e-77dabb222a03

@tripId = 

@previousRideId = 

### Ride Routes ###

### Create Ride Request
POST {{baseUrl}}/rides/request
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    "customerId": "{{customerId}}",
    "pickupLocation": {
        "lat": -1.9403,
        "lon": 30.0619,
        "address": "123 Main "
    },
    "dropoffLocation": {
        "lat": -1.9503,
        "lon": 30.0719,
        "address": "456 Elm St"
    }
}

### Accept Ride
PUT {{baseUrl}}/rides/accept
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "driverId": "{{driverId}}"
}

### Complete Ride
PUT {{baseUrl}}/rides/complete
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "finalAmount": 1105.456464858334
}

### Cancel Ride
PUT {{baseUrl}}/rides/cancel
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "tripId":"{{tripId}}",
  "canceledByType": "CUSTOMER",
  "canceledById": "{{customerId}}",
  "reason": "Customer changed their plans"
}

### Get Nearby Rides
GET {{baseUrl}}/rides/nearby?lat=-1.9403&lon=30.0619&radius=40
Authorization: Bearer {{driverToken}}

### Reorder Ride
POST {{baseUrl}}/rides/reorder
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "previousRideId": "{{previousRideId}}"
}
