@baseUrl = https://easy-ride-backend-xl8m.onrender.com/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4MDE0ZWExLWJkNzItNDBjOC1hZTNhLTA3NWU2ZTJkODU2MSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk3NzI2MDksImV4cCI6MTc0MjM2NDYwOX0.jHNgcuoKmNLzoDs9BlNIvYK2DTdbV8J2BeVmoC9F9Rk
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiMjc2Nzk2LTU2ZjAtNGE0ZC1iZWU4LTdjYTJkYTNhMTFjZSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5NzcyNjYyLCJleHAiOjE3NDIzNjQ2NjJ9.vmh0288p961zsIQJSibE-uujSacNNEBHib8fPxlcFFI

@customerId = e8014ea1-bd72-40c8-ae3a-075e6e2d8561

@driverId = 2b276796-56f0-4a4d-bee8-7ca2da3a11ce

@vehicleId = dbc00890-5d59-4572-8bc3-e4b10d09e8a1

@rideId = 2204aae8-6f84-4a97-8ef8-fd042a16bf7d

@tripId = f20dadba-60e1-4b7d-9158-1fc45cd677f2

@previousRideId = 82c96a16-054e-4915-8c48-28b721bc63d9

### Ride Routes ###

### Create Ride Request
POST {{baseUrl}}/rides/request
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
    "customerId": "{{customerId}}",
    "pickupLocation": {
        "lat": -1.9403,
        "lon": 30.0619,
        "address": "123 Main "
    },
    "dropoffLocation": {
        "lat": -1.9503,
        "lon": 30.0719,
        "address": "456 Elm St"
    }
}

### Accept Ride
PUT {{baseUrl}}/rides/accept
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "driverId": "{{driverId}}"
}

### Complete Ride
PUT {{baseUrl}}/rides/complete
Content-Type: application/json
Authorization: Bearer {{driverToken}}

{
  "rideId": "{{rideId}}",
  "finalAmount": 200.00 
}

### Cancel Ride
PUT {{baseUrl}}/rides/cancel
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "tripId":"{{tripId}}",
  "canceledByType": "CUSTOMER",
  "canceledById": "{{customerId}}",
  "reason": "Customer changed their plans"
}

### Get Nearby Rides
GET {{baseUrl}}/rides/nearby?lat=-1.9403&lon=30.0619&radius=40
Authorization: Bearer {{driverToken}}

### Reorder Ride
POST {{baseUrl}}/rides/reorder
Content-Type: application/json
Authorization: Bearer {{customerToken}}

{
  "previousRideId": "{{previousRideId}}"
}
