@baseUrl = https://easy-ride-backend-xl8m.onrender.com/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4MDE0ZWExLWJkNzItNDBjOC1hZTNhLTA3NWU2ZTJkODU2MSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk3NzI2MDksImV4cCI6MTc0MjM2NDYwOX0.jHNgcuoKmNLzoDs9BlNIvYK2DTdbV8J2BeVmoC9F9Rk
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiMjc2Nzk2LTU2ZjAtNGE0ZC1iZWU4LTdjYTJkYTNhMTFjZSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5NzcyNjYyLCJleHAiOjE3NDIzNjQ2NjJ9.vmh0288p961zsIQJSibE-uujSacNNEBHib8fPxlcFFI

@customerId = e8014ea1-bd72-40c8-ae3a-075e6e2d8561

@driverId = 2b276796-56f0-4a4d-bee8-7ca2da3a11ce

@vehicleId = dbc00890-5d59-4572-8bc3-e4b10d09e8a1

@rideId = 2204aae8-6f84-4a97-8ef8-fd042a16bf7d

@tripId = f20dadba-60e1-4b7d-9158-1fc45cd677f2

@previousRideId = 82c96a16-054e-4915-8c48-28b721bc63d9

### User Routes ###

### Get Customer Profile
GET {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}

###

### Get Driver Profile
GET {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update Customer Profile
PUT {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
    "name": "Updated Name",
    "phone": "+1987654321"
}

###

### Update Driver Profile
PUT {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
    "name": "Updated Driver Name",
    "phone": "+1987654321",
    "licenseNumber": "DL654321"
}

###

### Delete Customer Account
DELETE {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}

###

### Delete Driver Account
DELETE {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}

