@baseUrl = https://easy-ride-backend-xl8m.onrender.com/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlYWUxNWUwLTNjZGUtNDkxMC05NGM4LTUwYWYwMmYzNmRkOSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDA3NDE1NzAsImV4cCI6MTc0MzMzMzU3MH0.SJwDQAQD79IfTc35d4vxGXnV8i-QI1L1bRq2VHUhfEw

@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmYjBmMDY1LWIwYTktNDliZC05NjM4LWYzMTJkNzQ2OGQxNSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQwNzQxNjE0LCJleHAiOjE3NDMzMzM2MTR9.ppCV1Ins0zrODyGCd8T0oSsH2K9S4woETgS56X-8DPM

@customerId = 8eae15e0-3cde-4910-94c8-50af02f36dd9

@driverId = afb0f065-b0a9-49bd-9638-f312d7468d15

@vehicleId = f9e7fb4b-1028-4a35-9b0b-06bb3b94124d

@rideId = e1127483-ce1b-452e-ad9c-e4f09c30433a

@tripId = 924fa96c-503c-4e11-a111-a6fff19ced89

@previousRideId = 82c96a16-054e-4915-8c48-28b721bc63d9

### User Routes ###

### Get Customer Profile
GET {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}

###

### Get Driver Profile
GET {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update Customer Profile
PUT {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
    "name": "Updated Name",
    "phone": "+1987654321"
}

###

### Update Driver Profile
PUT {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
    "name": "Updated Driver Name",
    "phone": "+1987654321",
    "licenseNumber": "DL654321"
}

###

### Delete Customer Account
DELETE {{baseUrl}}/users/{{customerId}}
Authorization: Bearer {{customerToken}}

###

### Delete Driver Account
DELETE {{baseUrl}}/users/{{driverId}}
Authorization: Bearer {{driverToken}}

