@baseUrl = http://localhost:3000/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZjAxODRlLTBmOWYtNDc2Zi1hOTBmLTAxYmNmYWUyMjU4MSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NDA2Njg5NTMsImV4cCI6MTc0MzI2MDk1M30.JIoGtx4N7eosI6N4HHhvNXXJQF2SmbyOCh7eC15ZnXw
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyZTExOTQ3LWE2YjMtNDk1Yy1iOTUwLTE1NjM1Zjk3YmFlYSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzQwNjY4OTg5LCJleHAiOjE3NDMyNjA5ODl9.RWDVxZub3iHGI3OOeIl9f7VlO5ofs90Hbb4RBqQXfOE

@customerId = 44f0184e-0f9f-476f-a90f-01bcfae22581

@driverId = a2e11947-a6b3-495c-b950-15635f97baea

@vehicleId = 33fbe171-1fef-4796-9929-e5b5618cb376



### Vehicle Routes ###

### Create a new vehicle
POST {{baseUrl}}/vehicles
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "type": "CAR",
  "regNo": "ABC9123",
  "model": "Camry",
  "color": "Gold"
}

###

### Get all vehicles for a specific driver
GET {{baseUrl}}/vehicles/driver/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update a vehicle
PUT {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "type": "CAR",
  "model": "Camry",
  "color": "Black",
  "isActive": true
}

###

### Delete a vehicle
DELETE {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}

