@baseUrl = http://localhost:3000/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxZWMyMTFhLWUwMzktNGZhZi05OTFkLTY2N2RlZTA1MGQzNSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk1MTc3NzEsImV4cCI6MTc0MjEwOTc3MX0.a3JyMcbOdg1TBAivhVJFO9P8yFt8z_QRpMKEUHPNudw
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4YWU5ODM3LTFkMGYtNDAyNC1iMzczLWJjYTNjYTY0NzZhZSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5NTE3Nzk5LCJleHAiOjE3NDIxMDk3OTl9.23rYk_ry_e_WIKhwSy4QW496sDJB_5wYe2Q_24iAfDQ

@customerId = 41ec211a-e039-4faf-991d-667dee050d35

@driverId = 38ae9837-1d0f-4024-b373-bca3ca6476ae

@vehicleId = 05aef665-4ebb-4c7b-8cf9-e30bae05f0ee

### Vehicle Routes ###

### Create a new vehicle
POST {{baseUrl}}/vehicles
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "type": "CAR",
  "regNo": "ABC123",
  "model": "Camry",
  "color": "Gold"
}

###

### Get all vehicles for a specific driver
GET {{baseUrl}}/vehicles/driver/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update a vehicle
PUT {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "type": "CAR",
  "model": "Camry",
  "color": "Black",
  "isActive": true
}

###

### Delete a vehicle
DELETE {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}

