@baseUrl = https://easy-ride-backend-xl8m.onrender.com/api
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4MDE0ZWExLWJkNzItNDBjOC1hZTNhLTA3NWU2ZTJkODU2MSIsInVzZXJUeXBlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk3NzI2MDksImV4cCI6MTc0MjM2NDYwOX0.jHNgcuoKmNLzoDs9BlNIvYK2DTdbV8J2BeVmoC9F9Rk
@driverToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiMjc2Nzk2LTU2ZjAtNGE0ZC1iZWU4LTdjYTJkYTNhMTFjZSIsInVzZXJUeXBlIjoiRFJJVkVSIiwiaWF0IjoxNzM5NzcyNjYyLCJleHAiOjE3NDIzNjQ2NjJ9.vmh0288p961zsIQJSibE-uujSacNNEBHib8fPxlcFFI

@customerId = e8014ea1-bd72-40c8-ae3a-075e6e2d8561

@driverId = 2b276796-56f0-4a4d-bee8-7ca2da3a11ce

@vehicleId = dbc00890-5d59-4572-8bc3-e4b10d09e8a1



### Vehicle Routes ###

### Create a new vehicle
POST {{baseUrl}}/vehicles
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "driverId": "{{driverId}}",
  "type": "CAR",
  "regNo": "ABC9123",
  "model": "Camry",
  "color": "Gold"
}

###

### Get all vehicles for a specific driver
GET {{baseUrl}}/vehicles/driver/{{driverId}}
Authorization: Bearer {{driverToken}}

###

### Update a vehicle
PUT {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}
Content-Type: application/json

{
  "type": "CAR",
  "model": "Camry",
  "color": "Black",
  "isActive": true
}

###

### Delete a vehicle
DELETE {{baseUrl}}/vehicles/{{vehicleId}}
Authorization: Bearer {{driverToken}}

